#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=pmhc_8k_xray_aligned_egnn
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=60:00:00

module purge
module 2021
module load Anaconda3/2021.05

source activate mol

cd $HOME/ECGDM/

# Loop through fold numbers 1 to 10
for i in {1..10}; do
    data_dir="/gpfs/home4/dfruhbus/ECGDM/Data/Peptide_data/pmhc_xray_8K_aligned/folds/fold_${i}/"
    log_dir="./Experiments/Structure_prediction/Logs_Experiments/fold${i}/"
    output_file="../Outs/train_outs_new/fold_${i}_output.out"

    echo "Running fold $i with:"
    echo "  Data directory: $data_dir"
    echo "  Log directory: $log_dir"
    echo "  Output file: $output_file"

    srun --output="$output_file" \
         python -u Experiments/Structure_prediction/train.py \
         --config Experiments/Structure_prediction/configs/pmhc_8K_xray_aligned_egnn.yml \
         --data_dir "$data_dir" \
         --logdir "$log_dir"
done
