#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=test_pmhc_8K_egnn
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=00:10:00
#SBATCH --output=../Outs/pmhc_8K_egnn_5

module purge
module 2021
module load Anaconda3/2021.05

source activate mol

cd $HOME/ECGDM/
srun python -u Experiments/Structure_prediction/test.py --config Experiments/Structure_prediction/configs/SP_pmhc_8K_egnn.yml
