#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=pmhc_8k_egnn_small
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=05:00:00
#SBATCH --output=../Outs/train_outs_new/pmhc_8k_egnn_small_tanhF.out

module purge
module 2021
module load Anaconda3/2021.05

source activate mol

cd $HOME/ECGDM/
srun python -u Experiments/Structure_prediction/train.py --config Experiments/Structure_prediction/configs/pmhc_8K_egnn_small.yml