#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=pmhc_egnn_A_min
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=04:00:00
#SBATCH --output=../Outs/pmhc_egnn_ca_train_A_min.out

module purge
module 2021
module load Anaconda3/2021.05

source activate ecgdm

cd $HOME/ECGDM/
srun python -u Experiments/Structure_prediction/train_minimal.py --config Experiments/Structure_prediction/configs/SP_pmhc_egnn_min.yml

# srun python -u Experiments/Structure_prediction/test.py --config Experiments/Structure_prediction/configs/SP_pmhc_egnn.yml
